os:
  - linux
services:
  - docker
install:
  - docker version
  - docker build -t jhipster/generator .
script:
  - docker run -u jhipster --name jhipster -w /home/jhipster/app -p 8080:8080 -p 3000:3000 -p 3001:3001 -d -t jhipster/generator
  - docker ps
  - docker logs jhipster
  - chmod -R 777 $TRAVIS_BUILD_DIR/travis
  - docker cp $TRAVIS_BUILD_DIR/travis/.yo-rc.json jhipster:/home/jhipster/app/
  - docker cp $TRAVIS_BUILD_DIR/travis/.config jhipster:/home/jhipster/
  - docker exec -u jhipster -it jhipster ls -al /home/jhipster
  - docker exec -u jhipster -it jhipster ls -al /home/jhipster/app
  - docker exec -u jhipster -it jhipster ls -al /home/jhipster/.config/configstore/
  - docker exec -u jhipster -it jhipster yo jhipster --force --no-insight
  - docker exec -u jhipster -it jhipster ls -al /home/jhipster/app
  - docker images
