sudo: required
services:
  - docker
before_install:
  - sudo service docker restart ; sleep 10
install:
  - docker build -t jhipster/generator .
script:
  - cd travis
  - docker run -it --rm --user jhipster --name jhispter -v "$PWD":/home/jhipster/app -w /home/jhipster/app jhipster/generator yo jhipster --inforce --no-insight
  - ls -al
